sed -i '' 's/C:\/\//\/Users\/hoangnguyen\/Documents\/Bitbucket\//g' opsupport_bpm/aco/simulation/test_single_pnml_only.py
sed -i '' 's/C:\/\//\/Users\/hoangnguyen\/Documents\/Bitbucket\//g' opsupport_bpm/aco/aco_pheromone.py
sed -i '' 's/C:\/\//\/Users\/hoangnguyen\/Documents\/Bitbucket\//g' opsupport_bpm/aco/simulation/simulation_hgr_only.py
sed -i '' 's/C:\/\//\/Users\/hoangnguyen\/Documents\/Bitbucket\//g' opsupport_bpm/util/print_hypergraph.py
sed -i '' 's/C:\/\//\/Users\/hoangnguyen\/Documents\/Bitbucket\//g' opsupport_bpm/models/pnml_to_hypergraph.py
sed -i '' 's/C:\/\//\/Users\/hoangnguyen\/Documents\/Bitbucket\//g' opsupport_bpm/aco/simulation/GUI_simulation_main.py
sed -i '' 's/C:\/\//\/Users\/hoangnguyen\/Documents\/Bitbucket\//g' opsupport_bpm/aco/aco_pheromone.py
sed -i '' 's/C:\/\//\/Users\/hoangnguyen\/Documents\/Bitbucket\//g' opsupport_bpm/models/bpmn_to_hypergraph.py
sed -i '' 's/C:\/\//\/Users\/hoangnguyen\/Documents\/Bitbucket\//g' opsupport_bpm/aco/simulation/simulation_pnml_only.py
sed -i '' 's/C:\/\//\/Users\/hoangnguyen\/Documents\/Bitbucket\//g' opsupport_bpm/aco/simulation/test_single_hgr_only.py
